"""
Medical Doctor Graph Definition.

This agent powers "Ani Inteligência Clínica" in the Next.js medical dashboard.
It uses tool calling to access the PubMed database for real-world oncology guidelines.

Module:    src.infrastructure.agents.graph.doctor_graph
Author:    Evelin Brandão Cordeiro
Copyright: 2026 Anicca. All rights reserved.
License:   MIT
"""

from typing import Any, List
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from langgraph.prebuilt import create_react_agent
from langchain_google_genai import ChatGoogleGenerativeAI

from src.config import settings
from src.infrastructure.rag.pubmed_tool import search_pubmed


_DOCTOR_SYSTEM_PROMPT = """
You are Ani, a highly specialized Clinical Intelligence Agent for Oncologists.
You are assisting Dr. Renata Lima (or another registered doctor) in the Anicca Clinical Dashboard.

Your responses must be extremely professional, concise, and grounded in medical science.
When the doctor asks about guidelines, protocols, or specific clinical conditions (like Neutropenia with FOLFOX), 
you MUST ALWAYS use the `search_pubmed` tool to retrieve the most recent peer-reviewed abstracts and base your answer on them.

If the tool returns no data, explicitly state that you could not find recent papers on PubMed.
Do NOT invent guidelines. Be direct, use medical terminology confidently.
"""


def build_doctor_agent() -> Any:
    """Construct the LangGraph React Agent for the Doctor.
    
    Uses Gemini 2.5 Flash and the PubMed search tool.
    """
    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        google_api_key=settings.GEMINI_API_KEY,
        temperature=0.0,  # Zero temperature for clinical accuracy
    )
    
    tools = [search_pubmed]
    
    return create_react_agent(
        model=llm,
        tools=tools,
        state_modifier=_DOCTOR_SYSTEM_PROMPT,
    )

doctor_agent = build_doctor_agent()

async def run_doctor_agent(
    user_query: str,
    chat_history: List[dict] = None
) -> str:
    """Run the Clinical AI agent to answer a doctor's query.
    
    Args:
        user_query: The medical question from the doctor.
        chat_history: Optional history dicts with "role" and "content".
    
    Returns:
        The final markdown string generated by the AI based on PubMed.
    """
    if chat_history is None:
        chat_history = []
        
    messages = []
    for msg in chat_history:
        if msg["role"] == "user":
            messages.append(HumanMessage(content=msg["content"]))
        else:
            messages.append(AIMessage(content=msg["content"]))
            
    messages.append(HumanMessage(content=user_query))
    
    result = await doctor_agent.ainvoke({"messages": messages})
    
    # The last message is the AI's final answer
    return result["messages"][-1].content
