// ─────────────────────────────────────────────────────────────────────────────
// Document Types
// Domain: Medical documents, OCR results, file categorization
// ─────────────────────────────────────────────────────────────────────────────

/** Document categories for auto-cataloging by AI */
export type DocumentCategory =
  | 'pathology_biopsy' // Patologia e Biópsia (highest priority)
  | 'imaging' // Imagem (CT, MRI, PET-CT, US, X-Ray)
  | 'lab_results' // Resultado de Exames Laboratoriais
  | 'prescription' // Receita / Prescrição
  | 'medical_report' // Laudo Médico
  | 'treatment_protocol' // Protocolo de Tratamento
  | 'surgical_report' // Relatório Cirúrgico
  | 'discharge_summary' // Alta Hospitalar
  | 'referral' // Encaminhamento
  | 'authorization' // Autorização (APAC, convênio)
  | 'consent_form' // Termo de Consentimento
  | 'rnds_export' // Exportação do Meu SUS Digital
  | 'other';

/** OCR extraction result from AWS Textract */
export interface OcrResult {
  rawText: string;
  /** Extracted structured data (depends on document type) */
  extractedData?: {
    /** For pathology reports */
    primaryDiagnosis?: string;
    biradsCategory?: string; // BIRADS for mammography
    gleasonScore?: string; // For prostate
    cid10Code?: string; // CID-10 code
    /** For lab results */
    labValues?: Array<{
      name: string;
      value: string;
      unit: string;
      referenceRange?: string;
      isAbnormal?: boolean;
    }>;
    /** Key findings extracted by LLM */
    keyFindings?: string[];
    /** 3 suggested questions for the doctor (generated by LLM) */
    suggestedDoctorQuestions?: string[];
  };
  confidence: number; // 0–1
  processingStatus: 'pending' | 'processing' | 'completed' | 'failed';
}

/** A medical document uploaded by the patient */
export interface MedicalDocument {
  id: string;
  patientId: string;
  category: DocumentCategory;
  title: string;
  /** Original file name */
  fileName: string;
  fileType: 'pdf' | 'jpg' | 'jpeg' | 'png' | 'heic';
  fileSizeBytes: number;
  /** Signed S3 URL (time-limited) */
  fileUrl: string;
  /** Thumbnail URL for list display */
  thumbnailUrl?: string;
  /** Date on the document itself (not upload date) */
  documentDate?: string; // ISO 8601
  uploadedAt: string;
  /** Whether this document has been shared with the linked doctor */
  sharedWithDoctor: boolean;
  ocrResult?: OcrResult;
  /** Tags for search */
  tags: string[];
  /** Summary in CEFR A2 pt-BR generated by LLM */
  aiSummary?: string;
  /** Key highlighted finding */
  keyFinding?: string;
  isArchived: boolean;
}
