// ─────────────────────────────────────────────────────────────────────────────
// Journal Entry Types
// Domain: Emotional journaling, mood check-ins, wellbeing exercises
// ─────────────────────────────────────────────────────────────────────────────

/** Mood levels (4 options for simplicity — CEFR A2 compatible) */
export type MoodLevel = 'great' | 'okay' | 'difficult' | 'very_difficult';

/** Types of wellbeing exercises offered by Ani */
export type WellbeingExerciseType =
  | 'breathing_4_7_8' // 4-7-8 breathing technique
  | 'body_scan' // Body scan meditation
  | 'gratitude' // Gratitude reflection
  | 'grounding_5_4_3_2_1' // 5-4-3-2-1 grounding technique
  | 'progressive_relaxation'; // Progressive muscle relaxation

/** A wellbeing exercise session */
export interface WellbeingExercise {
  type: WellbeingExerciseType;
  startedAt: string;
  completedAt?: string;
  durationSeconds?: number;
}

/** A complete journal entry (nightly check-in) */
export interface JournalEntry {
  id: string;
  patientId: string;
  /** Date of the check-in (YYYY-MM-DD) */
  date: string;
  createdAt: string;
  updatedAt: string;
  mood: MoodLevel;
  /** The contextual prompt generated by Ani (based on clinical context) */
  aniPrompt: string;
  /** Free-text written by the patient — always private by default */
  freeText?: string;
  /** Whether the patient consented to share this with their doctor */
  sharedWithDoctor: boolean;
  /** Wellbeing exercise completed in this session */
  wellbeingExercise?: WellbeingExercise;
  /** Clinical context injected by Ani at the time of journaling */
  clinicalContext?: {
    currentCycle?: number;
    recentCtcaeGrades?: Array<{ symptomId: string; grade: number }>;
    daysSinceLastAppointment?: number;
  };
}

/** Mood trend over a period */
export interface MoodTrend {
  startDate: string;
  endDate: string;
  entries: Pick<JournalEntry, 'date' | 'mood'>[];
  /** Rolling 7-day mood score (0–100) */
  weeklyScore: number;
  trend: 'improving' | 'stable' | 'declining';
}
