"""Add doctor_patients association table

Revision ID: 078d559b050e
Revises: 2fd48a2b58ae
Create Date: 2026-08-30 16:27:51.552289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078d559b050e'
down_revision: Union[str, None] = '2fd48a2b58ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_patients',
    sa.Column('doctor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_doctor_patients_doctor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_doctor_patients_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', 'patient_id', name=op.f('pk_doctor_patients'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_patients')
    # ### end Alembic commands ###
