"""add_avatar_config

Revision ID: 0b71841eab79
Revises: 3e9e11aaf251
Create Date: 2026-08-08 16:39:20.850896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_avatar_config

Revision ID: 0b71841eab79
Revises: 3e9e11aaf251
Create Date: 2026-08-08 16:39:20.850896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b71841eab79'
down_revision: Union[str, None] = '3e9e11aaf251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_config')
    # ### end Alembic commands ###
