"""autogenerate_missing_tables

Revision ID: 3e9e11aaf251
Revises: 7e41cdd768f3
Create Date: 2026-08-08 16:19:06.984924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e9e11aaf251'
down_revision: Union[str, None] = '7e41cdd768f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journaling_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=False),
    sa.Column('text_encrypted', sa.Text(), nullable=True),
    sa.Column('ctcae_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shared_with_doctor', sa.Boolean(), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_journaling_entries_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journaling_entries'))
    )
    op.create_index(op.f('ix_journaling_entries_patient_id'), 'journaling_entries', ['patient_id'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('hydration_glasses', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wearable_steps', sa.Integer(), nullable=True),
    sa.Column('wearable_hrv', sa.Float(), nullable=True),
    sa.Column('wearable_resting_hr', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_routines_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    op.create_index(op.f('ix_routines_date'), 'routines', ['date'], unique=False)
    op.create_index(op.f('ix_routines_patient_id'), 'routines', ['patient_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('crm_number', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('expo_push_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_users_patient_id_patients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('consents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('term_version', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('source_channel', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('ai_questions', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ai_questions')
    op.drop_column('documents', 'source_channel')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_routines_patient_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_date'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_journaling_entries_patient_id'), table_name='journaling_entries')
    op.drop_table('journaling_entries')
    # ### end Alembic commands ###
