"""Add title and key_finding to documents

Revision ID: 5897ba7925c4
Revises: 078d559b050e
Create Date: 2026-08-31 22:05:31.645643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5897ba7925c4'
down_revision: Union[str, None] = '078d559b050e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('documents', sa.Column('key_finding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'key_finding')
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###
