"""Initial migration

Revision ID: 86be6c2cdcc3
Revises: 
Create Date: 2026-05-30 04:58:07.633428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86be6c2cdcc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name_encrypted', sa.Text(), nullable=False),
    sa.Column('cpf_hash', sa.String(length=64), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('cancer_type', sa.String(length=100), nullable=False),
    sa.Column('cancer_stage', sa.String(length=20), nullable=False),
    sa.Column('treatment_modality', sa.String(length=20), nullable=False),
    sa.Column('treatment_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('journey_phase', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_date', sa.String(length=10), nullable=True),
    sa.Column('ani_personality', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_cpf_hash'), 'patients', ['cpf_hash'], unique=False)
    op.create_index(op.f('ix_patients_whatsapp_phone'), 'patients', ['whatsapp_phone'], unique=True)
    op.create_table('body_map_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('body_region', sa.String(length=50), nullable=False),
    sa.Column('body_view', sa.String(length=10), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('symptom_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suggested_ctcae_grade', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_body_map_entries_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_map_entries'))
    )
    op.create_index(op.f('ix_body_map_entries_patient_id'), 'body_map_entries', ['patient_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('cards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agents_invoked', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_messages_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('institution_email', sa.String(length=200), nullable=True),
    sa.Column('protocol_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_tickets_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index(op.f('ix_tickets_patient_id'), 'tickets', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_patient_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_body_map_entries_patient_id'), table_name='body_map_entries')
    op.drop_table('body_map_entries')
    op.drop_index(op.f('ix_patients_whatsapp_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_cpf_hash'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
