"""Add Trust Layer and CV models

Revision ID: b5630574698a
Revises: 8ecbf978d11b
Create Date: 2026-08-30 16:06:33.514776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5630574698a'
down_revision: Union[str, None] = '8ecbf978d11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_map_entries', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('body_map_entries', sa.Column('cv_classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('body_map_entries', sa.Column('cv_processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body_map_entries', 'cv_processed_at')
    op.drop_column('body_map_entries', 'cv_classification')
    op.drop_column('body_map_entries', 'photo_url')
    # ### end Alembic commands ###
